### ISSUE TITLE
@extDB3 extension support

### ISSUE THREAD

**Issue by m1kesk** [fugasjunior/arma-server-manager#137]
Current build does not support arma 3 extension `extDB3`

Add dependencies to image for arma 3 server to use extDB3 extension

According to documentation, linux / windows images needed these dependencies:

Windows Requirement

Visual Studio C++ Redistributable 2019 32bit + 64bit version https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
Linux Requirement

Requirements Glibc Version 2.17+ Centos7+ / Debian 8+ / Ubuntu 14.10+

Deb Package System

apt-get install libtbb2:i386 and apt-get install libtbbmalloc2 

RPM Package System

yum install tbb.i686 and yum install tbb

**Comment by Xehia** [comment]
Yes, you can use @extDB3, just install `libtbbmalloc2` inside the container.

Add these lines in your `docker-compose.yml`
```
 entrypoint: >
      /bin/sh -c "apt-get update && apt-get install -y libtbbmalloc2 && apt-get clean && java -jar ./app.jar"
```


Place these lines under the network_mode, like this:
```
armaservermanager:
    image: "fugasjunior/armaservermanager:${VERSION}"
    restart: always
    # 'host' network mode is not available on Windows. If you need to run this image on Windows, you need to set up port mappings manually.
    network_mode: host
    entrypoint: >
          /bin/sh -c "apt-get update && apt-get install -y libtbbmalloc2 && apt-get clean && java -jar ./app.jar"
```
