### ISSUE TITLE
Deploy on windows Server 2025

### ISSUE THREAD

**Issue by TollerEmil** [fugasjunior/arma-server-manager#161]
**Describe the bug**
On my windows Server 2025 the docker-compose.exe -up command trows the error: yaml: line 22: did not find expected key.
In my case line 21 is "armaservermanager"

**Environment**
**OS**: Windows

**docker-compose.yml**
```
services:
  db:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DB_NAME}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - armaservermanager-db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"
 
  armaservermanager:
    image: "fugasjunior/armaservermanager:${VERSION}"
    restart: always
    # 'host' network mode is not available on Windows. If you need to run this image on Windows, you need to set up port mappings manually.
    # network_mode: host
    # uncomment when running on Windows and add additional ports according to your needs
        ports:
          - "8080:8080"
          - "2302-2305:2302-2305/udp"
          - "27016:27016/udp"
    depends_on:
      - db
    volumes:
      - "${STORAGE_PATH}:/home/steam/armaservermanager/"
    environment:
      AUTH_USERNAME: "${AUTH_USERNAME}"
      AUTH_PASSWORD: "${AUTH_PASSWORD}"
      SPRING_DATASOURCE_URL: "${MYSQL_DB_URL}"
      SPRING_DATASOURCE_USERNAME: "${MYSQL_USER}"
      SPRING_DATASOURCE_PASSWORD: "${MYSQL_PASSWORD}"
      STEAM_API_KEY: "${STEAM_API_KEY}"
      JWT_SECRET: "${JWT_SECRET}"
      DATABASE_ENCRYPTION_SECRET: "${DATABASE_ENCRYPTION_SECRET}"
      TZ: "${TIMEZONE}"

volumes:
  armaservermanager-db:
```

**.env**
```
# App version
VERSION=latest

# Change the path where the servers files and mods will be stored on your server
STORAGE_PATH=E:\\Arma_Server\\TEST

# Username and password for accessing the web interface
AUTH_USERNAME=<USERNAME>
AUTH_PASSWORD=<PASSWORD>

# Database settings. Make sure to change the password and root password
MYSQL_DB_NAME=armaservermanager_db
MYSQL_DB_URL=jdbc:mysql://localhost:3306/armaservermanager_db
# For Windows, use the following URL instead:
# MYSQL_DB_URL=jdbc:mysql://db:3306/armaservermanager_db
MYSQL_USER=armaservermanager
MYSQL_PASSWORD=<PASSWORD>
MYSQL_ROOT_PASSWORD=<PASSWORD>

# Steam API key, needed for Steam Workshop interaction.
# Generated with https://steamcommunity.com/dev/apikey.
STEAM_API_KEY= 

# JWT secret
# Used for creating JSON web tokens for app authentication.
# Any string can be used as a secret. The secret should be at least 32 characters long.
JWT_SECRET= <KEY>

# (OPTIONAL) Database encryption secret used for encrypting the Steam account password inside the database.
# Must be a valid AES 256-bit key (https://www.allkeysgenerator.com/Random/Security-Encryption-Key-Generator.aspx).
# This setting is optional. In case the secret is not provided, the password will be stored in plain text form.
# Also make sure there are no '$' symbols in the secret which cause issues when being passed through the .env file
DATABASE_ENCRYPTION_SECRET=

# Set the right Timezone from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones, example Europe/London , US/Pacific , etc
TIMEZONE= Europe/Berlin
```
