### ISSUE TITLE
Issues setting up docker container with windows

### ISSUE THREAD

**Issue by stevenpi** [fugasjunior/arma-server-manager#82]
Hey there!

I'm having trouble setting the project up on Windows 10. 
I cloned the project, and tried to setup the docker containers using docker compose. 
When I try to connect to `localhost:8080` with my webbrowser (Brave), the website fails to load (not found, as if no server would exist).

This is what powershell prints after starting up the docker container:
```
PS D:\ArmaServerManager\arma-server-manager\TestServer> docker compose up
[+] Running 3/0
 - Container testserver-adminer-1            Created                                                                                                                                                        0.0s
 - Container testserver-db-1                 Created                                                                                                                                                        0.0s
 - Container testserver-armaservermanager-1  Recreated                                                                                                                                                      0.1s
Attaching to testserver-adminer-1, testserver-armaservermanager-1, testserver-db-1
testserver-adminer-1            | [Tue Oct 17 15:20:35 2023] PHP 7.4.33 Development Server (http://[::]:8080) started
testserver-db-1                 | 2023-10-17 15:20:35+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.1.0-1.el8 started.
testserver-db-1                 | 2023-10-17 15:20:35+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
testserver-db-1                 | 2023-10-17 15:20:35+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.1.0-1.el8 started.
testserver-db-1                 | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
testserver-db-1                 | 2023-10-17T15:20:36.025784Z 0 [System] [MY-015015] [Server] MySQL Server - start.
testserver-db-1                 | 2023-10-17T15:20:36.214426Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
testserver-db-1                 | 2023-10-17T15:20:36.215444Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.1.0) starting as process 1
testserver-db-1                 | 2023-10-17T15:20:36.220517Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
testserver-db-1                 | 2023-10-17T15:20:36.312462Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
testserver-db-1                 | 2023-10-17T15:20:36.491508Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
testserver-db-1                 | 2023-10-17T15:20:36.491558Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
testserver-db-1                 | 2023-10-17T15:20:36.494673Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
testserver-db-1                 | 2023-10-17T15:20:36.507838Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
testserver-db-1                 | 2023-10-17T15:20:36.507910Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.1.0'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
testserver-armaservermanager-1  |
testserver-armaservermanager-1  |   .   ____          _            __ _ _
testserver-armaservermanager-1  |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
testserver-armaservermanager-1  | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
testserver-armaservermanager-1  |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
testserver-armaservermanager-1  |   '  |____| .__|_| |_|_| |_\__, | / / / /
testserver-armaservermanager-1  |  =========|_|==============|___/=/_/_/_/
testserver-armaservermanager-1  |  :: Spring Boot ::                (v2.7.5)
testserver-armaservermanager-1  |
testserver-armaservermanager-1  | 2023-10-17 15:20:36,729 INFO  org.springframework.boot.StartupInfoLogger: Starting ServerManagerApplication using Java 17.0.7 on docker-desktop with PID 1 (/home/steam/app.jar started by root in /home/steam)
testserver-armaservermanager-1  | 2023-10-17 15:20:36,729 INFO  org.hibernate.validator.internal.util.Version: HV000001: Hibernate Validator 6.2.5.Final
testserver-armaservermanager-1  | 2023-10-17 15:20:36,732 INFO  org.springframework.boot.SpringApplication: The following 1 profile is active: "docker"
testserver-armaservermanager-1  | 2023-10-17 15:20:37,286 INFO  org.springframework.data.repository.config.RepositoryConfigurationDelegate: Bootstrapping Spring Data JPA repositories in DEFAULT mode.
testserver-armaservermanager-1  | 2023-10-17 15:20:37,348 INFO  org.springframework.data.repository.config.RepositoryConfigurationDelegate: Finished Spring Data repository scanning in 55 ms. Found 6 JPA repository interfaces.
testserver-armaservermanager-1  | 2023-10-17 15:20:37,818 INFO  org.springframework.boot.web.embedded.tomcat.TomcatWebServer: Tomcat initialized with port(s): 8080 (http)
testserver-armaservermanager-1  | 2023-10-17 15:20:37,826 INFO  org.apache.juli.logging.DirectJDKLog: Initializing ProtocolHandler ["http-nio-8080"]
testserver-armaservermanager-1  | 2023-10-17 15:20:37,826 INFO  org.apache.juli.logging.DirectJDKLog: Starting service [Tomcat]
testserver-armaservermanager-1  | 2023-10-17 15:20:37,827 INFO  org.apache.juli.logging.DirectJDKLog: Starting Servlet engine: [Apache Tomcat/9.0.68]
testserver-armaservermanager-1  | 2023-10-17 15:20:37,878 INFO  org.apache.juli.logging.DirectJDKLog: Initializing Spring embedded WebApplicationContext
testserver-armaservermanager-1  | 2023-10-17 15:20:37,879 INFO  org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext: Root WebApplicationContext: initialization completed in 1106 ms
testserver-armaservermanager-1  | 2023-10-17 15:20:38,019 INFO  org.flywaydb.core.internal.logging.slf4j.Slf4jLog: Flyway Community Edition 9.6.0 by Redgate
testserver-armaservermanager-1  | 2023-10-17 15:20:38,019 INFO  org.flywaydb.core.internal.logging.slf4j.Slf4jLog: See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#9.6.0
testserver-armaservermanager-1  | 2023-10-17 15:20:38,019 INFO  org.flywaydb.core.internal.logging.slf4j.Slf4jLog:
testserver-armaservermanager-1  | 2023-10-17 15:20:38,027 INFO  com.zaxxer.hikari.HikariDataSource: HikariPool-1 - Starting...
testserver-armaservermanager-1  | 2023-10-17 15:20:38,308 INFO  com.zaxxer.hikari.HikariDataSource: HikariPool-1 - Start completed.
testserver-armaservermanager-1  | 2023-10-17 15:20:38,331 INFO  org.flywaydb.core.internal.logging.slf4j.Slf4jLog: Database: jdbc:mysql://localhost:3306/armaservermanager_db (MySQL 8.1)
testserver-armaservermanager-1  | 2023-10-17 15:20:38,359 WARN  org.flywaydb.core.internal.logging.slf4j.Slf4jLog: Flyway upgrade recommended: MySQL 8.1 is newer than this version of Flyway and support has not been tested. The latest supported version of MySQL is 8.0.
testserver-armaservermanager-1  | 2023-10-17 15:20:38,388 INFO  org.flywaydb.core.internal.logging.slf4j.Slf4jLog: Successfully validated 2 migrations (execution time 00:00.022s)
testserver-armaservermanager-1  | 2023-10-17 15:20:38,400 INFO  org.flywaydb.core.internal.logging.slf4j.Slf4jLog: Current version of schema `armaservermanager_db`: 1.1.0
testserver-armaservermanager-1  | 2023-10-17 15:20:38,401 INFO  org.flywaydb.core.internal.logging.slf4j.Slf4jLog: Schema `armaservermanager_db` is up to date. No migration necessary.
testserver-armaservermanager-1  | 2023-10-17 15:20:38,459 INFO  org.hibernate.jpa.internal.util.LogHelper: HHH000204: Processing PersistenceUnitInfo [name: default]
testserver-armaservermanager-1  | 2023-10-17 15:20:38,491 INFO  org.hibernate.Version: HHH000412: Hibernate ORM core version 5.6.12.Final
testserver-armaservermanager-1  | 2023-10-17 15:20:38,636 INFO  org.hibernate.annotations.common.reflection.java.JavaReflectionManager: HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
testserver-armaservermanager-1  | 2023-10-17 15:20:38,706 INFO  org.hibernate.dialect.Dialect: HHH000400: Using dialect: org.hibernate.dialect.MySQL8Dialect
testserver-armaservermanager-1  | 2023-10-17 15:20:38,821 ERROR cz.forgottenempire.servermanager.common.AttributeEncryptor: The provided AES database encryption key is not invalid, proceeding without encryption. (Cause: Invalid AES key length: 64 bytes)
testserver-armaservermanager-1  | 2023-10-17 15:20:39,303 INFO  org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformInitiator: HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
testserver-armaservermanager-1  | 2023-10-17 15:20:39,308 INFO  org.springframework.orm.jpa.AbstractEntityManagerFactoryBean: Initialized JPA EntityManagerFactory for persistence unit 'default'
testserver-armaservermanager-1  | 2023-10-17 15:20:39,706 INFO  cz.forgottenempire.servermanager.workshop.UpdateModsCronJob: Scheduling mod update cronjob for 03:00 AM every day
testserver-armaservermanager-1  | 2023-10-17 15:20:39,849 WARN  org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration: spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
testserver-armaservermanager-1  | 2023-10-17 15:20:39,883 ERROR cz.forgottenempire.servermanager.common.AttributeEncryptor: The provided AES database encryption key is not invalid, proceeding without encryption. (Cause: Invalid AES key length: 64 bytes)
testserver-armaservermanager-1  | 2023-10-17 15:20:40,086 INFO  org.springframework.security.web.DefaultSecurityFilterChain: Will secure any request with [org.springframework.security.web.session.DisableEncodeUrlFilter@19b02dfd, org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@3dce6dd8, org.springframework.security.web.context.SecurityContextPersistenceFilter@66e17eff, org.springframework.security.web.header.HeaderWriterFilter@73c48264, org.springframework.web.filter.CorsFilter@69f2cb04, org.springframework.security.web.authentication.logout.LogoutFilter@519c6fcc, cz.forgottenempire.servermanager.security.JWTAuthenticationFilter@13803a94, cz.forgottenempire.servermanager.security.JWTAuthorizationFilter@b4732dc, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@1bbddada, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@3421debd, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@45292ec1, org.springframework.security.web.session.SessionManagementFilter@5bcec67e, org.springframework.security.web.access.ExceptionTranslationFilter@6b2dd3df, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@3292d91a]
testserver-armaservermanager-1  | 2023-10-17 15:20:40,207 INFO  org.springframework.boot.autoconfigure.web.servlet.WelcomePageHandlerMapping: Adding welcome page: class path resource [static/index.html]
testserver-armaservermanager-1  | 2023-10-17 15:20:40,375 INFO  org.apache.juli.logging.DirectJDKLog: Starting ProtocolHandler ["http-nio-8080"]
testserver-armaservermanager-1  | 2023-10-17 15:20:40,386 INFO  org.springframework.boot.web.embedded.tomcat.TomcatWebServer: Tomcat started on port(s): 8080 (http) with context path ''
testserver-armaservermanager-1  | 2023-10-17 15:20:40,397 INFO  org.springframework.boot.StartupInfoLogger: Started ServerManagerApplication in 4.027 seconds (JVM running for 4.361)
Gracefully stopping... (press Ctrl+C again to force)
[+] Running 3/3
 - Container testserver-armaservermanager-1  Stopped                                                                                                                                                        0.1s
 - Container testserver-adminer-1            Stopped                                                                                                                                                        0.6s
 - Container testserver-db-1                 Stopped                                                                                                                                                        1.1s
canceled
```

In the `docker-compose.yml` file i noticed the comment, that i have to setup the ports myself on windows. Therefore I edited the `docker-compose.yml` like this:

```
version: '3.3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DB_NAME}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - armaservermanager-db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"

  armaservermanager:
    image: "fugasjunior/armaservermanager:${VERSION}"
    restart: always
    #    Not available on Windows. If you need to run this image on Windows, you need to set up port mappings manually.
    network_mode: host
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      #      - /home/armaservermanager/storage:/home/steam/armaservermanager/
      - armaservermanager-storage:/home/steam/armaservermanager/
    environment:
      AUTH_USERNAME: "${AUTH_USERNAME}"
      AUTH_PASSWORD: "${AUTH_PASSWORD}"
      SPRING_DATASOURCE_URL: "${MYSQL_DB_URL}"
      SPRING_DATASOURCE_USERNAME: "${MYSQL_USER}"
      SPRING_DATASOURCE_PASSWORD: "${MYSQL_PASSWORD}"
      STEAM_API_KEY: "${STEAM_API_KEY}"
      JWT_SECRET: "${JWT_SECRET}"
      DATABASE_ENCRYPTION_SECRET: "${DATABASE_ENCRYPTION_SECRET}"

volumes:
  armaservermanager-db:
  armaservermanager-storage:
```

I also setup the `.env` file by providing the according auth keys.

Am I missing something?

**Comment by trollhus** [comment]
Can't tell much by from the logs. But also, very important, I'm only a user and not really experienced enough with docker but I think you need to change your volumes.  

You should probably point to something like C:/users/blablabla/:/home/steam/armaservermanager/
I'm using below but I'm  on linux. 
volumes:
      #      - /home/armaservermanager/storage:/home/steam/armaservermanager/
      - /srv/fast/arma3server/arma3server/:/home/steam/armaservermanager/

**Comment by stevenpi** [comment]
I set the volumes an gave them an according path. thanks for noticing. but this didn't solve the issue.

I looked more at the comment stating "Not available on Windows. If you need to run this image on Windows, you need to set up port mappings manually" which is refering to the line `network_mode: host`.

I tried to mess with the docker compose file.
I noticed that I setup the ports wrong, the `armaservermanager` service exposes the 8080 port (in the file i set it to 80). 
But this does not solve the issue either unfortunately. 

When I comment out `network: host`, the `armaservermanager` container exits and restarts because it cannot establish a connection to the database.

Any other idea where the issue could be?

for people interested, this is the current `docker-compose.yml` file (with updated volumes and port):

```
version: '3.3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DB_NAME}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - armaservermanager-db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"

  armaservermanager:
    image: "fugasjunior/armaservermanager:${VERSION}"
    restart: always
    #    Not available on Windows. If you need to run this image on Windows, you need to set up port mappings manually.
    # network_mode: host
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      #      - /home/armaservermanager/storage:/home/steam/armaservermanager/
      - armaservermanager-storage:/home/steam/armaservermanager/
    environment:
      AUTH_USERNAME: "${AUTH_USERNAME}"
      AUTH_PASSWORD: "${AUTH_PASSWORD}"
      SPRING_DATASOURCE_URL: "${MYSQL_DB_URL}"
      SPRING_DATASOURCE_USERNAME: "${MYSQL_USER}"
      SPRING_DATASOURCE_PASSWORD: "${MYSQL_PASSWORD}"
      STEAM_API_KEY: "${STEAM_API_KEY}"
      JWT_SECRET: "${JWT_SECRET}"
      DATABASE_ENCRYPTION_SECRET: "${DATABASE_ENCRYPTION_SECRET}"

volumes:
  armaservermanager-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: D:\ArmaServerManager\arma-server-manager\TestServer\volumeDB
  armaservermanager-storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: D:\ArmaServerManager\arma-server-manager\TestServer\volumeServer
```

**Comment by fugasjunior** [comment]
Hi @stevenpi, would you mind also sharing your `.env` file (with the sensitive data removed, of course)?

I'm unfortunately no Docker expert either, but from what I can tell:
- I would definitely remove the `network_mode: host` on Windows
- You don't need to expose ports in the DB service. Docker creates internal network  for the services defined in the compose file with its own DNS, where the service name is used as the container hostname. So you can remove the `ports: - "3306:3306"`
- That being said, you should have the database URL as `MYSQL_DB_URL=jdbc:mysql://db:3306/armaservermanager_db` in the `.env` file (notice the hostname is **`db`**)

I was able to get the whole app running with the exact docker-compose file you've sent in your last post by using the following `.env` file:

```.env
VERSION=latest

AUTH_USERNAME=test
AUTH_PASSWORD=test

MYSQL_DB_NAME=armaservermanager_db
MYSQL_DB_URL=jdbc:mysql://db:3306/armaservermanager_db
MYSQL_USER=armaservermanager
MYSQL_PASSWORD=example
MYSQL_ROOT_PASSWORD=change_me

STEAM_API_KEY=.....
JWT_SECRET=.....
DATABASE_ENCRYPTION_SECRET=.....
```

**Comment by stevenpi** [comment]
Thank you for your reply, I got it now working :D

It was indeed an error in the .env file. I had the MYSQL_DB_URL set to `jdbc:mysql://localhost:3306/armaservermanager_db`
changing it to `jdbc:mysql://db:3306/armaservermanager_db` as you suggested, fixed the error. 
Thanks for your help!

Just for future reference, i will copy my compose file and the according (save) env file one last time. Maybe this helps other people in the future:

docker-compose.yml:

```
version: '3.3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DB_NAME}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - armaservermanager-db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"

  armaservermanager:
    image: "fugasjunior/armaservermanager:${VERSION}"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      #      - /home/armaservermanager/storage:/home/steam/armaservermanager/
      - armaservermanager-storage:/home/steam/armaservermanager/
    environment:
      AUTH_USERNAME: "${AUTH_USERNAME}"
      AUTH_PASSWORD: "${AUTH_PASSWORD}"
      SPRING_DATASOURCE_URL: "${MYSQL_DB_URL}"
      SPRING_DATASOURCE_USERNAME: "${MYSQL_USER}"
      SPRING_DATASOURCE_PASSWORD: "${MYSQL_PASSWORD}"
      STEAM_API_KEY: "${STEAM_API_KEY}"
      JWT_SECRET: "${JWT_SECRET}"
      DATABASE_ENCRYPTION_SECRET: "${DATABASE_ENCRYPTION_SECRET}"

volumes:
  armaservermanager-db:
  armaservermanager-storage:
```

the according .env file (with fake example data for not getting hacked lol):

```
# App version
VERSION=latest

# Username and password for accessing the web interface
AUTH_USERNAME=some_test_user
AUTH_PASSWORD=some_test_password

# Database settings. Make sure to change the password and root password
MYSQL_DB_NAME=armaservermanager_db
MYSQL_DB_URL=jdbc:mysql://db:3306/armaservermanager_db # <--  changed "localhost" to "db"
MYSQL_USER=armaservermanager_user
MYSQL_PASSWORD=example_password
MYSQL_ROOT_PASSWORD=make_a_better_pw_do_not_copy

# Steam API key, needed for Steam Workshop interaction.
# Generated with https://steamcommunity.com/dev/apikey.
STEAM_API_KEY=getitfromthelink

# JWT secret
# Used for creating JSON web tokens for app authentication.
# Any string can be used as a secret. The secret should be at least 32 characters long.
JWT_SECRET=somerandomstringandstuffsasdfgfg

# (OPTIONAL) Database encryption secret used for encrypting the Steam account password inside the database.
# Must be a valid AES 256-bit key (https://www.allkeysgenerator.com/Random/Security-Encryption-Key-Generator.aspx).
# This setting is optional. In case the secret is not provided, the password will be stored in plain text form.
# Also make sure there are no '$' symbols in the secret which cause issues when being passed through the .env file
DATABASE_ENCRYPTION_SECRET=
```
