### ISSUE TITLE
How can the server be reached in arma 3?

### ISSUE THREAD

**Issue by CubelightCodes** [fugasjunior/arma-server-manager#89]
Hey there,

I managed to setup the app with steam auth, installing arma 3 server and adding a scenario and mods and configuring the server. But it does not show up under direct connect with the vps server IP and 2302 port, and i also cant query it by keywords. Do i have to open ports first? According to logs it seems to be running

The app currently runs in a network with nginx proxy manager and is served over it.

Here my configurations below:
![image](https://github.com/fugasjunior/arma-server-manager/assets/72654359/0b23f034-71e5-4d18-9419-eb0f7ef1b1ff)
![image](https://github.com/fugasjunior/arma-server-manager/assets/72654359/49334696-a2d2-4e61-9067-5f5a729a1180)

**Comment by fugasjunior** [comment]
Hi, would you mind sharing more info about the VPS and your setup such as your OS, whether you're running the manager in Docker or natively and whether you use the host network mode or expose specific ports?

In the meantime, by using Nginx Proxy Manager, I'll assume that you use Docker with only exposing specific ports. In such case, you need to expose ports `2302` (server port) and `2303` (steam query port) directly from the Arma server manager docker service. You also need to make sure that the ports are open and not blocked by any kind of firewall.

**Comment by CubelightCodes** [comment]
Hi, the VPS has a Ubuntu 22.04. LTS OS and I run the manager via docker fully. The special thing is that I changed the compose yaml file so that all containers join a common docker network with the nginx proxy manager. This is necessary so that NPM can expose the container to the web and add a certificate for example (You and I discussed earlier about documenting a reverse proxy setup to secure the arma manager for public accessibility -> Maybe I am soon ready to write one having maneuvered myself painfully through everything :D). As of my understanding currently all of the containers are exposed to the web also without proxy (I know its bad practice with the db being open to the web on 3306, but I am setting this up for testing purposes).

Here is the specified docker compose yaml for the arma server manager

```
version: '3.3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DB_NAME}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      - nginx-proxy-manager_default
    ports:
      - "3306:3306"
    volumes:
      - armaservermanager-db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    networks:
      - nginx-proxy-manager_default
    ports:
      - "8090:8080"

  armaservermanager:
    image: "fugasjunior/armaservermanager:${VERSION}"
    restart: always
    #    Not available on Windows. If you need to run this image on Windows, you need to set up port mappings manually.
    # network_mode: host
    networks:
      - nginx-proxy-manager_default
    depends_on:
      - db
    volumes:
      #      - /home/armaservermanager/storage:/home/steam/armaservermanager/
      - armaservermanager-storage:/home/steam/armaservermanager/
    environment:
      AUTH_USERNAME: "${AUTH_USERNAME}"
      AUTH_PASSWORD: "${AUTH_PASSWORD}"
      SPRING_DATASOURCE_URL: "${MYSQL_DB_URL}"
      SPRING_DATASOURCE_USERNAME: "${MYSQL_USER}"
      SPRING_DATASOURCE_PASSWORD: "${MYSQL_PASSWORD}"
      STEAM_API_KEY: "${STEAM_API_KEY}"
      JWT_SECRET: "${JWT_SECRET}"
      DATABASE_ENCRYPTION_SECRET: "${DATABASE_ENCRYPTION_SECRET}"

networks:
  nginx-proxy-manager_default:
    external: true

volumes:
  armaservermanager-db:
  armaservermanager-storage:
```

  
  Additionally the nginx proxy manager configuration for the proxy host:
  
  
![image](https://github.com/fugasjunior/arma-server-manager/assets/72654359/f24be550-9a86-459b-b550-fc169f3679fd)

  
  Is there anything specific I could provide? `docker ps` or `docker network inspect` results or something?

**Comment by CubelightCodes** [comment]
So, no I disabled the network_mode: host as it was incompatible with networking together with NPM. What do you mean by opening the 2302/2303 ports from the arma server manager docker configuration? I am new to docker and docker compose, what specifically should be updated in my upper yaml file?

**Comment by fugasjunior** [comment]
Thanks for the info. In such case, you definitely need to expose server ports in the `docker-compose.yml` file. I'm not aware of any method which would allow you to proxy the traffic to Arma server ports through Nginx proxy manager.

You need to add something like:
```
ports:
  - "2302:2302"
  - "2303:2303"
```
to the armaservermanager service. In your case, the file would look like this:
```yml
version: '3.3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DB_NAME}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      - nginx-proxy-manager_default
    ports:
      - "3306:3306"
    volumes:
      - armaservermanager-db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    networks:
      - nginx-proxy-manager_default
    ports:
      - "8090:8080"

  armaservermanager:
    image: "fugasjunior/armaservermanager:${VERSION}"
    restart: always
    #    Not available on Windows. If you need to run this image on Windows, you need to set up port mappings manually.
    # network_mode: host
    networks:
      - nginx-proxy-manager_default
    ports:
      - "2302:2302"
      - "2303:2303"
    depends_on:
      - db
    volumes:
      #      - /home/armaservermanager/storage:/home/steam/armaservermanager/
      - armaservermanager-storage:/home/steam/armaservermanager/
    environment:
      AUTH_USERNAME: "${AUTH_USERNAME}"
      AUTH_PASSWORD: "${AUTH_PASSWORD}"
      SPRING_DATASOURCE_URL: "${MYSQL_DB_URL}"
      SPRING_DATASOURCE_USERNAME: "${MYSQL_USER}"
      SPRING_DATASOURCE_PASSWORD: "${MYSQL_PASSWORD}"
      STEAM_API_KEY: "${STEAM_API_KEY}"
      JWT_SECRET: "${JWT_SECRET}"
      DATABASE_ENCRYPTION_SECRET: "${DATABASE_ENCRYPTION_SECRET}"

networks:
  nginx-proxy-manager_default:
    external: true

volumes:
  armaservermanager-db:
  armaservermanager-storage:
```

Keep in mind that if you change these ports or add more servers running on different ports, you also need to reflect the changes in the `docker-compose.yml` file.

By the way, great job with setting up the Nginx proxy manager! I'm using it on other projects and it would definitely be my go-to way of setting up HTTPS for the server manager now.
